In [ ]:
!pip install supabase

Collecting supabase
  Downloading supabase-2.29.0-py3-none-any.whl.metadata (4.6 kB)
Collecting realtime==2.29.0 (from supabase)
  Downloading realtime-2.29.0-py3-none-any.whl.metadata (7.0 kB)
Collecting supabase-functions==2.29.0 (from supabase)
  Downloading supabase_functions-2.29.0-py3-none-any.whl.metadata (2.4 kB)
Collecting storage3==2.29.0 (from supabase)
  Downloading storage3-2.29.0-py3-none-any.whl.metadata (2.1 kB)
Collecting supabase-auth==2.29.0 (from supabase)
  Downloading supabase_auth-2.29.0-py3-none-any.whl.metadata (6.4 kB)
Collecting postgrest==2.29.0 (from supabase)
  Downloading postgrest-2.29.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: httpx<0.29,>=0.26 in /usr/local/lib/python3.12/dist-packages (from supabase) (0.28.1)
Requirement already satisfied: yarl>=1.22.0 in /usr/local/lib/python3.12/dist-packages (from supabase) (1.23.0)
Requirement already satisfied: deprecation>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from postgrest==2.29.0->supabase) (2.1.0)
Requirement already satisfied: pydantic<3.0,>=1.9 in /usr/local/lib/python3.12/dist-packages (from postgrest==2.29.0->supabase) (2.12.3)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from realtime==2.29.0->supabase) (4.15.0)
Requirement already satisfied: websockets<16,>=11 in /usr/local/lib/python3.12/dist-packages (from realtime==2.29.0->supabase) (15.0.1)
Requirement already satisfied: pyiceberg>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from storage3==2.29.0->supabase) (0.11.1)
Requirement already satisfied: pyjwt>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->supabase-auth==2.29.0->supabase) (2.12.1)
Collecting strenum>=0.4.15 (from supabase-functions==2.29.0->supabase)
  Downloading StrEnum-0.4.15-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<0.29,>=0.26->supabase) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<0.29,>=0.26->supabase) (0.16.0)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.12/dist-packages (from yarl>=1.22.0->supabase) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from yarl>=1.22.0->supabase) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from deprecation>=2.1.0->postgrest==2.29.0->supabase) (26.1)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]<0.29,>=0.26->postgrest==2.29.0->supabase) (4.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.29.0->supabase) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.29.0->supabase) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0,>=1.9->postgrest==2.29.0->supabase) (0.4.2)
Requirement already satisfied: mmh3<6.0.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.29.0->supabase) (5.2.1)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.29.0->supabase) (2.32.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.29.0->supabase) (8.3.3)
Requirement already satisfied: rich<15.0.0,>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.29.0->supabase) (13.9.4)
Requirement already satisfied: strictyaml<2.0.0,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.29.0->supabase) (1.7.3)
Requirement already satisfied: fsspec>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.29.0->supabase) (2025.3.0)
Requirement already satisfied: pyparsing<4.0.0,>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.29.0->supabase) (3.3.2)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.29.0->supabase) (9.1.4)
Requirement already satisfied: pyroaring<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.29.0->supabase) (1.0.4)
Requirement already satisfied: cachetools<7.0,>=5.5 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.29.0->supabase) (6.2.6)
Requirement already satisfied: zstandard<1.0.0,>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from pyiceberg>=0.10.0->storage3==2.29.0->supabase) (0.25.0)
Requirement already satisfied: cryptography>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->supabase-auth==2.29.0->supabase) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->supabase-auth==2.29.0->supabase) (2.0.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.29.0->supabase) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]<0.29,>=0.26->postgrest==2.29.0->supabase) (4.1.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg>=0.10.0->storage3==2.29.0->supabase) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->pyiceberg>=0.10.0->storage3==2.29.0->supabase) (2.5.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.29.0->supabase) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.29.0->supabase) (2.20.0)
Requirement already satisfied: python-dateutil>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from strictyaml<2.0.0,>=1.7.0->pyiceberg>=0.10.0->storage3==2.29.0->supabase) (2.9.0.post0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=3.4.0->pyjwt[crypto]>=2.10.1->supabase-auth==2.29.0->supabase) (3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=10.11.0->pyiceberg>=0.10.0->storage3==2.29.0->supabase) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.6.0->strictyaml<2.0.0,>=1.7.0->pyiceberg>=0.10.0->storage3==2.29.0->supabase) (1.17.0)
Downloading supabase-2.29.0-py3-none-any.whl (16 kB)
Downloading postgrest-2.29.0-py3-none-any.whl (22 kB)
Downloading realtime-2.29.0-py3-none-any.whl (22 kB)
Downloading storage3-2.29.0-py3-none-any.whl (28 kB)
Downloading supabase_auth-2.29.0-py3-none-any.whl (48 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 2.9 MB/s eta 0:00:00
Downloading supabase_functions-2.29.0-py3-none-any.whl (8.8 kB)
Downloading StrEnum-0.4.15-py3-none-any.whl (8.9 kB)
Installing collected packages: strenum, realtime, supabase-functions, supabase-auth, storage3, postgrest, supabase
Successfully installed postgrest-2.29.0 realtime-2.29.0 storage3-2.29.0 strenum-0.4.15 supabase-2.29.0 supabase-auth-2.29.0 supabase-functions-2.29.0

In [ ]:
from supabase import create_client

SUPABASE_URL = "https://duttpmxhiq...supabase.co"
SUPABASE_KEY = "sb_publishable_xxxxx"  # tu key completa

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

print("Conectado a Supabase")

Conectado a Supabase

In [ ]:
df = pd.read_csv("camaras_cctv_limpia.csv", encoding="latin-1")

In [ ]:
encoding="utf-8-sig"

In [ ]:
print(df.columns)

Index(['objectid', 'direccion', 'localizacion', 'longitud', 'latitud',
       'x_origen_nacional', 'y_origen_nacional'],
      dtype='object')

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

df = pd.read_csv("velocidad_trafico_limpia.csv", encoding="utf-8-sig")

df.info()
df.isnull().sum()
df.duplicated().sum()
df.head()

/tmp/ipykernel_20125/2362809181.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("velocidad_trafico_limpia.csv", encoding="utf-8-sig")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681302 entries, 0 to 681301
Data columns (total 20 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ID               681302 non-null  object
 1   FECHA_HORA       681302 non-null  object
 2   TV_[S]           681302 non-null  int64
 3   CORREDOR         681302 non-null  int64
 4   DÃA             681302 non-null  int64
 5   MES              681302 non-null  int64
 6   AÃ‘O             681302 non-null  int64
 7   HORA             681302 non-null  int64
 8   FECHA            681302 non-null  object
 9   NOMBRE_CORREDOR  681302 non-null  object
 10  FLUJO_TIPO       681302 non-null  object
 11  SENTIDO          681302 non-null  object
 12  INICIO           681302 non-null  object
 13  FIN              681302 non-null  object
 14  LONGITUD_KM      681302 non-null  float64
 15  TV_MINUTOS       681302 non-null  float64
 16  VELOCIDAD_KM_H   681302 non-null  float64
 17  TV_MIN_KM        681302 non-null  float64
 18  DIASEM           681302 non-null  int64
 19  NOMBRE_DÃA      681302 non-null  object
dtypes: float64(4), int64(7), object(9)
memory usage: 104.0+ MB

,ID,FECHA_HORA,TV_[S],CORREDOR,DÃA,MES,AÃ‘O,HORA,FECHA,NOMBRE_CORREDOR,FLUJO_TIPO,SENTIDO,INICIO,FIN,LONGITUD_KM,TV_MINUTOS,VELOCIDAD_KM_H,TV_MIN_KM,DIASEM,NOMBRE_DÃA
0,1210,1/02/2017 6:00,377,2,1,2,2017,6,1/02/2017,AVENIDA REGIONAL,CONTINUO,SN,TUGO,SAN JUAN,6.6,6.3,63.0,1.0,3,MIï¿½RCOLES
1,1212,1/02/2017 6:00,495,4,1,2,2017,6,1/02/2017,AUTOPISTA SUR,CONTINUO,NS,CTI,CALLE 10,6.5,8.3,47.0,1.3,3,MIï¿½RCOLES
2,1213,1/02/2017 6:00,495,5,1,2,2017,6,1/02/2017,AUTOPISTA NORTE,CONTINUO,NS,SOLLA,PUNTO CERO,5.3,8.3,39.0,1.6,3,MIï¿½RCOLES
3,1214,1/02/2017 6:00,401,6,1,2,2017,6,1/02/2017,AUTOPISTA NORTE,CONTINUO,SN,PUNTO CERO,SOLLA,5.3,6.7,48.0,1.3,3,MIï¿½RCOLES
4,1215,1/02/2017 6:00,693,7,1,2,2017,6,1/02/2017,AVENIDA 80,INTERRUMPIDO,NS,CALLE 65,CALLE 30,5.1,11.6,26.0,2.3,3,MIï¿½RCOLES

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("velocidad_trafico_limpia.csv", encoding="utf-8-sig")

# 🔥 limpiar nombres de columnas sin romper encoding
df.columns = (
    df.columns
    .str.strip()
    .str.upper()
    .str.replace("Ã", "A")
    .str.replace("Ñ", "N")
    .str.replace("Í", "I")
    .str.replace("É", "E")
    .str.replace("Á", "A")
    .str.replace("Ó", "O")
    .str.replace("Ú", "U")
    .str.replace(" ", "_")
)

print(df.columns)

/tmp/ipykernel_20125/3484072506.py:4: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("velocidad_trafico_limpia.csv", encoding="utf-8-sig")

Index(['ID', 'FECHA_HORA', 'TV_[S]', 'CORREDOR', 'DAA', 'MES', 'AA‘O', 'HORA',
       'FECHA', 'NOMBRE_CORREDOR', 'FLUJO_TIPO', 'SENTIDO', 'INICIO', 'FIN',
       'LONGITUD_KM', 'TV_MINUTOS', 'VELOCIDAD_KM_H', 'TV_MIN_KM', 'DIASEM',
       'NOMBRE_DAA'],
      dtype='object')

In [ ]:
for col in df.select_dtypes(include="object").columns:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r"[^\x00-\x7F]+", "", regex=True)  # 🔥 elimina caracteres raros
        .str.strip()
        .str.upper()
    )

In [ ]:
print(df.columns)

Index(['ID', 'FECHA_HORA', 'TV_[S]', 'CORREDOR', 'DAA', 'MES', 'AA‘O', 'HORA',
       'FECHA', 'NOMBRE_CORREDOR', 'FLUJO_TIPO', 'SENTIDO', 'INICIO', 'FIN',
       'LONGITUD_KM', 'TV_MINUTOS', 'VELOCIDAD_KM_H', 'TV_MIN_KM', 'DIASEM',
       'NOMBRE_DAA'],
      dtype='object')

In [ ]:
df.columns = (
    df.columns
    .str.strip()
    .str.upper()
    .str.replace("Ã\x8d", "I", regex=False)   # Í mal codificada
    .str.replace("Ã\x91", "N", regex=False)   # Ñ mal codificada
    .str.replace("Ã", "A", regex=False)
    .str.replace(" ", "_")
)

print(df.columns)

Index(['ID', 'FECHA_HORA', 'TV_[S]', 'CORREDOR', 'DAA', 'MES', 'AA‘O', 'HORA',
       'FECHA', 'NOMBRE_CORREDOR', 'FLUJO_TIPO', 'SENTIDO', 'INICIO', 'FIN',
       'LONGITUD_KM', 'TV_MINUTOS', 'VELOCIDAD_KM_H', 'TV_MIN_KM', 'DIASEM',
       'NOMBRE_DAA'],
      dtype='object')

In [ ]:
def fix_text(text):
    try:
        return text.encode('latin1').decode('utf-8')
    except:
        return text

In [ ]:
df.columns = [fix_text(col) for col in df.columns]

# luego normalizamos
df.columns = (
    df.columns
    .str.strip()
    .str.upper()
    .str.replace(" ", "_")
)

print(df.columns)

Index(['ID', 'FECHA_HORA', 'TV_[S]', 'CORREDOR', 'DAA', 'MES', 'AA‘O', 'HORA',
       'FECHA', 'NOMBRE_CORREDOR', 'FLUJO_TIPO', 'SENTIDO', 'INICIO', 'FIN',
       'LONGITUD_KM', 'TV_MINUTOS', 'VELOCIDAD_KM_H', 'TV_MIN_KM', 'DIASEM',
       'NOMBRE_DAA'],
      dtype='object')

In [ ]:
df = df.rename(columns={
    'DAA': 'DIA',
    'AA‘O': 'ANO',
    'NOMBRE_DAA': 'NOMBRE_DIA'
})

In [ ]:
cols = list(df.columns)

cols[4] = "DIA"
cols[6] = "ANO"
cols[-1] = "NOMBRE_DIA"

df.columns = cols

print(df.columns)

Index(['ID', 'FECHA_HORA', 'TV_[S]', 'CORREDOR', 'DIA', 'MES', 'ANO', 'HORA',
       'FECHA', 'NOMBRE_CORREDOR', 'FLUJO_TIPO', 'SENTIDO', 'INICIO', 'FIN',
       'LONGITUD_KM', 'TV_MINUTOS', 'VELOCIDAD_KM_H', 'TV_MIN_KM', 'DIASEM',
       'NOMBRE_DIA'],
      dtype='object')

In [ ]:
print(df["NOMBRE_DIA"].value_counts())
print(df["SENTIDO"].value_counts())
print(df["FLUJO_TIPO"].value_counts())

NOMBRE_DIA
MARTES      102366
LUNES       102051
MIRCOLES    101380
VIERNES     101110
JUEVES      100808
SBADO        87238
DOMINGO      86349
Name: count, dtype: int64
SENTIDO
NS    245691
SN    245597
WE     95014
EW     95000
Name: count, dtype: int64
FLUJO_TIPO
INTERRUMPIDO    488073
CONTINUO        193229
Name: count, dtype: int64

In [ ]:
df["NOMBRE_DIA"] = df["NOMBRE_DIA"].replace({
    "MIRCOLES": "MIERCOLES",
    "SBADO": "SABADO"
})

In [ ]:
print(df["NOMBRE_DIA"].value_counts())

NOMBRE_DIA
MARTES       102366
LUNES        102051
MIERCOLES    101380
VIERNES      101110
JUEVES       100808
SABADO        87238
DOMINGO       86349
Name: count, dtype: int64

In [ ]:
dias_validos = ["LUNES","MARTES","MIERCOLES","JUEVES","VIERNES","SABADO","DOMINGO"]

df = df[df["NOMBRE_DIA"].isin(dias_validos)]

hasta aqui llega la primera base

In [ ]:
import pandas as pd

df = pd.read_csv("paradas_limpia.csv", encoding="utf-8-sig")

df.info()
df.isnull().sum()
df.duplicated().sum()

df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10043 entries, 0 to 10042
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OBJECTID             10043 non-null  object
 1   SHAPE                0 non-null      float64
 2   ID_PARADERO          0 non-null      float64
 3   ID_PARADA            0 non-null      float64
 4   ID_RUTA              0 non-null      float64
 5   NRO_PARADA           0 non-null      float64
 6   DIRECCION            0 non-null      float64
 7   TIPO_PARADA          0 non-null      float64
 8   RECORRIDO            0 non-null      float64
 9   CODIGO_RUTA          0 non-null      float64
 10  NOMBRE_RUTA          0 non-null      float64
 11  SISTEMA_RUTA         0 non-null      float64
 12  TIPO_RUTA            0 non-null      float64
 13  EMPRESA              0 non-null      float64
 14  LONGITUD             0 non-null      float64
 15  LATITUD              0 non-null      float64
 16  X_ORIGEN_NACIONAL    0 non-null      float64
 17  Y_ORIGEN_NACIONAL    0 non-null      float64
 18  FECHA_ACTUALIZACION  0 non-null      float64
dtypes: float64(18), object(1)
memory usage: 1.5+ MB

,OBJECTID,SHAPE,ID_PARADERO,ID_PARADA,ID_RUTA,NRO_PARADA,DIRECCION,TIPO_PARADA,RECORRIDO,CODIGO_RUTA,NOMBRE_RUTA,SISTEMA_RUTA,TIPO_RUTA,EMPRESA,LONGITUD,LATITUD,X_ORIGEN_NACIONAL,Y_ORIGEN_NACIONAL,FECHA_ACTUALIZACION
0,"1,""(4714862.777400001, 2252165.179200001)"",525...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"2,""(4712457.373900001, 2246019.061400002)"",515...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"3,""(4714362.8133, 2254170.956700003)"",52335,90...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"4,""(4716295.369699999, 2241767.274700001)"",534...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"5,""(4716643.501500001, 2249802.825200001)"",536...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(df.select_dtypes(include="object").columns)

Index(['OBJECTID'], dtype='object')

In [ ]:
print(df["tipo_parada"].value_counts())
print(df["tipo_ruta"].value_counts())
print(df["recorrido"].value_counts())

KeyError: 'tipo_parada'

In [ ]:
df = pd.read_csv("paradas_limpia.csv", encoding="utf-8-sig", sep=";")

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10043 entries, 0 to 10042
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                   Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                   --------------  -----
 0   OBJECTID,SHAPE,ID_PARADERO,ID_PARADA,ID_RUTA,NRO_PARADA,DIRECCION,TIPO_PARADA,RECORRIDO,CODIGO_RUTA,NOMBRE_RUTA,SISTEMA_RUTA,TIPO_RUTA,EMPRESA,LONGITUD,LATITUD,X_ORIGEN_NACIONAL,Y_ORIGEN_NACIONAL,FECHA_ACTUALIZACION  10043 non-null  object
dtypes: object(1)
memory usage: 78.6+ KB

  OBJECTID,SHAPE,ID_PARADERO,ID_PARADA,ID_RUTA,NRO_PARADA,DIRECCION,TIPO_PARADA,RECORRIDO,CODIGO_RUTA,NOMBRE_RUTA,SISTEMA_RUTA,TIPO_RUTA,EMPRESA,LONGITUD,LATITUD,X_ORIGEN_NACIONAL,Y_ORIGEN_NACIONAL,FECHA_ACTUALIZACION
0  1,"(4714862.777400001, 2252165.179200001)",525...
1  2,"(4712457.373900001, 2246019.061400002)",515...
2  3,"(4714362.8133, 2254170.956700003)",52335,90...
3  4,"(4716295.369699999, 2241767.274700001)",534...
4  5,"(4716643.501500001, 2249802.825200001)",536...

In [ ]:
df = pd.read_csv("paradas_limpia.csv", encoding="utf-8-sig", sep=";")

In [ ]:
df = pd.read_csv("paradas_limpia.csv", encoding="utf-8-sig", sep=",", quotechar='"')

In [ ]:
df = pd.read_csv("paradas_limpia.csv", encoding="utf-8-sig", sep=None, engine="python")

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10043 entries, 0 to 10042
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OBJECTID             10043 non-null  object
 1   SHAPE                0 non-null      float64
 2   ID_PARADERO          0 non-null      float64
 3   ID_PARADA            0 non-null      float64
 4   ID_RUTA              0 non-null      float64
 5   NRO_PARADA           0 non-null      float64
 6   DIRECCION            0 non-null      float64
 7   TIPO_PARADA          0 non-null      float64
 8   RECORRIDO            0 non-null      float64
 9   CODIGO_RUTA          0 non-null      float64
 10  NOMBRE_RUTA          0 non-null      float64
 11  SISTEMA_RUTA         0 non-null      float64
 12  TIPO_RUTA            0 non-null      float64
 13  EMPRESA              0 non-null      float64
 14  LONGITUD             0 non-null      float64
 15  LATITUD              0 non-null      float64
 16  X_ORIGEN_NACIONAL    0 non-null      float64
 17  Y_ORIGEN_NACIONAL    0 non-null      float64
 18  FECHA_ACTUALIZACION  0 non-null      float64
dtypes: float64(18), object(1)
memory usage: 1.5+ MB

,OBJECTID,SHAPE,ID_PARADERO,ID_PARADA,ID_RUTA,NRO_PARADA,DIRECCION,TIPO_PARADA,RECORRIDO,CODIGO_RUTA,NOMBRE_RUTA,SISTEMA_RUTA,TIPO_RUTA,EMPRESA,LONGITUD,LATITUD,X_ORIGEN_NACIONAL,Y_ORIGEN_NACIONAL,FECHA_ACTUALIZACION
0,"1,""(4714862.777400001, 2252165.179200001)"",525...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"2,""(4712457.373900001, 2246019.061400002)"",515...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"3,""(4714362.8133, 2254170.956700003)"",52335,90...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"4,""(4716295.369699999, 2241767.274700001)"",534...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"5,""(4716643.501500001, 2249802.825200001)"",536...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd

df = pd.read_csv("paradas_de_transporte_pub.csv", encoding="latin-1", sep=None, engine="python")

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10043 entries, 0 to 10042
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OBJECTID             10043 non-null  int64
 1   Shape                10043 non-null  object
 2   id_paradero          10043 non-null  int64
 3   id_parada            10041 non-null  float64
 4   id_ruta              10043 non-null  int64
 5   nro_parada           10043 non-null  float64
 6   direccion            9960 non-null   object
 7   tipo_parada          10043 non-null  object
 8   recorrido            10043 non-null  object
 9   codigo_ruta          10043 non-null  object
 10  nombre_ruta          10043 non-null  object
 11  sistema_ruta         10043 non-null  object
 12  tipo_ruta            10043 non-null  object
 13  empresa              10003 non-null  object
 14  longitud             10043 non-null  float64
 15  latitud              10043 non-null  float64
 16  x_origen_nacional    10043 non-null  float64
 17  y_origen_nacional    10043 non-null  float64
 18  tipo_actoadmin       0 non-null      float64
 19  numero_actoadmin     0 non-null      float64
 20  anio_actoadmin       0 non-null      float64
 21  estado               12 non-null     object
 22  fecha_actualizacion  10043 non-null  object
dtypes: float64(9), int64(3), object(11)
memory usage: 1.8+ MB

,OBJECTID,Shape,id_paradero,id_parada,id_ruta,nro_parada,direccion,tipo_parada,recorrido,codigo_ruta,...,empresa,longitud,latitud,x_origen_nacional,y_origen_nacional,tipo_actoadmin,numero_actoadmin,anio_actoadmin,estado,fecha_actualizacion
0,1,"(4714862.777400001, 2252165.179200001)",52588,90098014.0,90098,14.0,"CR 68A x CL 78B, Medellin",Reglamentaria,Origen-Destino,260T,...,Palenque Robledal,-75.577979,6.275795,4.714863e+06,2.252165e+06,NaN,NaN,NaN,NaN,2018-08-01 00:00:00
1,2,"(4712457.373900001, 2246019.061400002)",51532,90003015.0,90003,15.0,"DG 79 9-133, Medellin",Reglamentaria,Origen-Destino,302,...,Autobuses Poblado Laureles,-75.599437,6.220123,4.712457e+06,2.246019e+06,NaN,NaN,NaN,NaN,2018-08-01 00:00:00
2,3,"(4714362.8133, 2254170.956700003)",52335,90075048.0,90075,48.0,"CL 95A x CR 79, Medellin",Reglamentaria,Destino-Origen,252,...,Palenque Robledal,-75.582585,6.293906,4.714363e+06,2.254171e+06,NaN,NaN,NaN,NaN,2018-08-01 00:00:00
3,4,"(4716295.369699999, 2241767.274700001)",53497,90010041.0,90010,41.0,"CR 25B x CL 18A, Medellin",Reglamentaria,Origen-Destino,305,...,Invetrans,-75.564579,6.181853,4.716295e+06,2.241767e+06,NaN,NaN,NaN,NaN,2018-08-01 00:00:00
4,5,"(4716643.501500001, 2249802.825200001)",53687,90014054.0,90014,54.0,"CL 58 45D-96, Medellin",Reglamentaria,Destino-Origen,309D,...,Coinvetrans,-75.561786,6.254516,4.716644e+06,2.249803e+06,NaN,NaN,NaN,NaN,2019-12-05 00:00:00

In [ ]:
import numpy as np

# reemplazar nulos
df = df.replace({np.nan: None})

# nombres de columnas limpios
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

# eliminar columnas inútiles
df = df.drop(columns=["shape"], errors="ignore")

In [ ]:
df = df.drop(columns=[
    "tipo_actoadmin",
    "numero_actoadmin",
    "anio_actoadmin"
], errors="ignore")

In [ ]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip().str.upper()

In [ ]:
print(df["tipo_parada"].value_counts())
print(df["tipo_ruta"].value_counts())
print(df["recorrido"].value_counts())
print(df["empresa"].value_counts().head())

tipo_parada
REGLAMENTARIA    10043
Name: count, dtype: int64
tipo_ruta
DIRECTA CENTRO       6476
INTEGRADA            1911
CIRCULAR             1163
DIRECTA NO CENTRO     493
Name: count, dtype: int64
recorrido
ORIGEN-DESTINO    5237
DESTINO-ORIGEN    4806
Name: count, dtype: int64
empresa
TRANSPORTE MEDELLÍN CASTILLA    1225
PALENQUE ROBLEDAL                877
TAX MAYA                         857
RÁPIDO SAN CRISTÓBAL             843
COONATRA                         826
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv("paradas_limpia_final.csv", index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

os.makedirs("/content/drive/MyDrive/RetoEafit/limpios", exist_ok=True)

In [ ]:
df.to_csv("/content/drive/MyDrive/RetoEafit/limpios/paradas_limpia_final.csv", index=False)

INICIO BD PARADAS LIMPIA

In [ ]:
df.to_csv("/content/drive/MyDrive/RetoEafit/limpios/velocidad_trafico_limpia_final.csv", index=False)

In [ ]:
import os
os.listdir("/content/drive/MyDrive/RetoEafit/limpios")

['paradas_limpia_final.csv', 'velocidad_trafico_limpia_final.csv']

In [ ]:
import os
os.listdir("/content/drive/MyDrive/RetoEafit/limpios")

['paradas_limpia_final.csv', 'velocidad_trafico_limpia_final.csv']

In [ ]:
import pandas as pd

df = pd.read_csv("camaras_cctv_limpia.csv", encoding="utf-8-sig")

df.info()
df.head()

ParserError: Error tokenizing data. C error: Expected 2 fields in line 76, saw 3

In [ ]:
df = pd.read_csv(
    "camaras_cctv_limpia.csv",
    encoding="utf-8-sig",
    sep=",",
    on_bad_lines="skip"
)

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, 1;(4711518.0712 to 81;(4715148.627100001
Data columns (total 1 columns):
 #   Column                                                                                                             Non-Null Count  Dtype
---  ------                                                                                                             --------------  -----
 0   OBJECTID;SHAPE;DIRECCION;LOCALIZACION;LINK_FOTO;LINK_DETALLE;LONGITUD;LATITUD;X_ORIGEN_NACIONAL;Y_ORIGEN_NACIONAL  80 non-null     object
dtypes: object(1)
memory usage: 1.2+ KB

                     OBJECTID;SHAPE;DIRECCION;LOCALIZACION;LINK_FOTO;LINK_DETALLE;LONGITUD;LATITUD;X_ORIGEN_NACIONAL;Y_ORIGEN_NACIONAL
1;(4711518.0712        2248071.1384999994);CR 83C CL 33;EL CASTILLO;...
2;(4711596.650000002   2249565.700700002);CR 89 CL 44;EVEREST;HTTPS:...
3;(4710266.759799999   2252278.7375000007);CR 108BB CL 62D;TÃšNEL DE...
4;(4714887.2167        2251605.745500002);CR 65 CL 71;LA FLORIDA;HTT...
5;(4707890.003300001   2252233.4857);CR 134 CL 59;VIVERO TÃšNEL DE O...

In [ ]:
df = pd.read_csv(
    "camaras_cctv_limpia.csv",
    encoding="utf-8-sig",
    sep=";",
    engine="python"
)

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OBJECTID           81 non-null     int64
 1   SHAPE              81 non-null     object
 2   DIRECCION          81 non-null     object
 3   LOCALIZACION       81 non-null     object
 4   LINK_FOTO          80 non-null     object
 5   LINK_DETALLE       80 non-null     object
 6   LONGITUD           80 non-null     object
 7   LATITUD            80 non-null     object
 8   X_ORIGEN_NACIONAL  80 non-null     object
 9   Y_ORIGEN_NACIONAL  80 non-null     object
dtypes: int64(1), object(9)
memory usage: 6.5+ KB

,OBJECTID,SHAPE,DIRECCION,LOCALIZACION,LINK_FOTO,LINK_DETALLE,LONGITUD,LATITUD,X_ORIGEN_NACIONAL,Y_ORIGEN_NACIONAL
0,1,"(4711518.0712, 2248071.1384999994)",CR 83C CL 33,EL CASTILLO,HTTPS://WWW.MEDELLIN.GOV.CO/SIMM/CAMARAS-CCTV/...,HTTPS://WWW.MEDELLIN.GOV.CO/SIMM/,-75.608.014,6.238.633,47.115.180.712,11.818.595.059
1,2,"(4711596.650000002, 2249565.700700002)",CR 89 CL 44,EVEREST,HTTPS://WWW.MEDELLIN.GOV.CO/SIMM/CAMARAS-CCTV/...,HTTPS://WWW.MEDELLIN.GOV.CO/SIMM/,-75.607.371,6.252.148,4711596.65,11.833.544.443
2,3,"(4710266.759799999, 2252278.7375000007)",CR 108BB CL 62D,TÃšNEL DE OCCIDENTE,HTTPS://WWW.MEDELLIN.GOV.CO/SIMM/CAMARAS-CCTV/...,HTTPS://WWW.MEDELLIN.GOV.CO/SIMM/,-75.619.508,6.276.615,47.102.667.598,11.860.609.532
3,4,"(4714887.2167, 2251605.745500002)",CR 65 CL 71,LA FLORIDA,HTTPS://WWW.MEDELLIN.GOV.CO/SIMM/CAMARAS-CCTV/...,HTTPS://WWW.MEDELLIN.GOV.CO/SIMM/,-75.577.733,6.270.738,47.148.872.167,11.854.105.811
4,5,"(4707890.003300001, 2252233.4857)",CR 134 CL 59,VIVERO TÃšNEL DE OCCIDENTE,HTTPS://WWW.MEDELLIN.GOV.CO/SIMM/CAMARAS-CCTV/...,HTTPS://WWW.MEDELLIN.GOV.CO/SIMM/,-75.640.979,6.276.098,47.078.900.033,11.860.040.601

In [ ]:
import numpy as np

# nulos
df = df.replace({np.nan: None})

# nombres de columnas
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [ ]:
import numpy as np

# nulos
df = df.replace({np.nan: None})

# nombres de columnas
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [ ]:
def fix_text(text):
    try:
        return text.encode('latin1').decode('utf-8')
    except:
        return text

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].apply(fix_text).str.strip().str.upper()

In [ ]:
df["localizacion"] = df["localizacion"].replace({
    "ZOOLGICO": "ZOOLOGICO",
    "TNEL DE OCCIDENTE": "TUNEL DE OCCIDENTE",
    "CALCAFE": "CALCAFE"
})

In [ ]:
df["link_detalle"].str.startswith("HTTP").value_counts()

link_detalle
True    80
Name: count, dtype: int64

In [ ]:
df.to_csv("/content/drive/MyDrive/RetoEafit/limpios/camaras_limpia_final.csv", index=False)

In [ ]:
import os
os.listdir("/content/drive/MyDrive/RetoEafit/limpios")

['paradas_limpia_final.csv',
 'velocidad_trafico_limpia_final.csv',
 'camaras_limpia_final.csv']

In [ ]:
import os
os.listdir("/content/drive/MyDrive/RetoEafit/limpios")

['paradas_limpia_final.csv',
 'velocidad_trafico_limpia_final.csv',
 'camaras_limpia_final.csv']

In [ ]:
df.isnull().sum()
df.duplicated().sum()
print(df.columns)

Index(['objectid', 'shape', 'direccion', 'localizacion', 'link_foto',
       'link_detalle', 'longitud', 'latitud', 'x_origen_nacional',
       'y_origen_nacional'],
      dtype='object')

In [ ]:
import numpy as np

df = df.replace({np.nan: None})

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [ ]:
import numpy as np

df = df.replace({np.nan: None})

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [ ]:
print(df["tipo"].value_counts())
print(df["recorrido"].value_counts())
print(df["empresa"].value_counts().head())

KeyError: 'tipo'

In [ ]:
print(df.columns)

Index(['objectid', 'shape', 'direccion', 'localizacion', 'link_foto',
       'link_detalle', 'longitud', 'latitud', 'x_origen_nacional',
       'y_origen_nacional'],
      dtype='object')

In [ ]:
df = pd.read_csv("rutas_limpia.csv", encoding="utf-8-sig")

In [ ]:
print(df.columns)
df.info()
df.head()

Index(['OBJECTID', 'SHAPE', 'NOMBRE', 'ID_RUTA', 'CODIGO', 'RECORRIDO',
       'FROM_DATE', 'SISTEMA', 'TIPO', 'EMPRESA', 'ID_GFLOTA', 'LONGITUD',
       'FECHA_ACTUALIZACION', 'SHAPE_LENGTH'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OBJECTID             249 non-null    object
 1   SHAPE                0 non-null      float64
 2   NOMBRE               0 non-null      float64
 3   ID_RUTA              0 non-null      float64
 4   CODIGO               0 non-null      float64
 5   RECORRIDO            0 non-null      float64
 6   FROM_DATE            0 non-null      float64
 7   SISTEMA              0 non-null      float64
 8   TIPO                 0 non-null      float64
 9   EMPRESA              0 non-null      float64
 10  ID_GFLOTA            0 non-null      float64
 11  LONGITUD             0 non-null      float64
 12  FECHA_ACTUALIZACION  0 non-null      float64
 13  SHAPE_LENGTH         0 non-null      float64
dtypes: float64(13), object(1)
memory usage: 27.4+ KB

,OBJECTID,SHAPE,NOMBRE,ID_RUTA,CODIGO,RECORRIDO,FROM_DATE,SISTEMA,TIPO,EMPRESA,ID_GFLOTA,LONGITUD,FECHA_ACTUALIZACION,SHAPE_LENGTH
0,"1,""(4715457.633850309, 2252270.912431034)"",12 ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"2,""(4715462.572997097, 2254279.9873374775)"",12...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"3,""(4716905.228793093, 2255044.7912288033)"",12...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"4,""(4710541.0989092905, 2249797.5061010984)"",2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"5,""(4716541.9905215055, 2249174.6770195253)"",A...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = pd.read_csv(
    "rutas_de_transporte_publi.csv",
    encoding="latin-1",
    sep=";"
)

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 1 columns):
 #   Column                                                                                                                             Non-Null Count  Dtype
---  ------                                                                                                                             --------------  -----
 0   OBJECTID,Shape,nombre,id_ruta,codigo,recorrido,from_date,sistema,tipo,empresa,id_gflota,longitud,fecha_actualizacion,Shape_Length  249 non-null    object
dtypes: object(1)
memory usage: 2.1+ KB

  OBJECTID,Shape,nombre,id_ruta,codigo,recorrido,from_date,sistema,tipo,empresa,id_gflota,longitud,fecha_actualizacion,Shape_Length
0  1,"(4715457.633850309, 2252270.912431034)",12 ...
1  2,"(4715462.572997097, 2254279.9873374775)",12...
2  3,"(4716905.228793093, 2255044.7912288033)",12...
3  4,"(4710541.0989092905, 2249797.5061010984)",2...
4  5,"(4716541.9905215055, 2249174.6770195253)",A...

In [ ]:
df = pd.read_csv(
    "rutas_de_transporte_publi.csv",
    encoding="latin-1",
    sep=",",
    quotechar='"',
    engine="python"
)

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OBJECTID             249 non-null    int64
 1   Shape                249 non-null    object
 2   nombre               249 non-null    object
 3   id_ruta              249 non-null    int64
 4   codigo               249 non-null    object
 5   recorrido            249 non-null    object
 6   from_date            249 non-null    object
 7   sistema              249 non-null    object
 8   tipo                 249 non-null    object
 9   empresa              249 non-null    object
 10  id_gflota            239 non-null    float64
 11  longitud             249 non-null    float64
 12  fecha_actualizacion  249 non-null    object
 13  Shape_Length         249 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 27.4+ KB

,OBJECTID,Shape,nombre,id_ruta,codigo,recorrido,from_date,sistema,tipo,empresa,id_gflota,longitud,fecha_actualizacion,Shape_Length
0,1,"(4715457.633850309, 2252270.912431034)",12 de Octubre - Calle 90,90111,263,Origen Destino_Destino Origen,2018-08-01 00:00:00,2B,Directa Centro,Transporte Medellín Castilla,110585.0,19982.069944,2024-12-10 05:11:05,17662.358980
1,2,"(4715462.572997097, 2254279.9873374775)",12 de Octubre - Estación Tricentenario,90113,263i,Origen Destino_Destino Origen,2024-08-27 00:00:00,2B,Integrada,Transporte Medellín Castilla,110712.0,8842.359411,2024-12-10 05:11:05,7138.797803
2,3,"(4716905.228793093, 2255044.7912288033)",12 de Octubre - Estación Tricentenario,90114,263ii,Origen Destino_Destino Origen,2024-08-27 00:00:00,2B,Integrada,Transporte Medellín Castilla,110722.0,2221.247902,2024-12-10 05:11:05,2221.247902
3,4,"(4710541.0989092905, 2249797.5061010984)",20 de Julio,90307,225i-1,Origen Destino_Destino Origen,2024-08-27 00:00:00,8A,Integrada,Metrosan,111912.0,3085.329774,2024-12-10 05:11:05,2279.247112
4,5,"(4716541.9905215055, 2249174.6770195253)",Alcázares de Sucre,90243,91,Origen Destino_Destino Origen,2024-08-27 00:00:00,6F,Directa Centro,Copatra,112915.0,17688.836117,2024-12-10 05:11:05,13085.209787

In [ ]:
import numpy as np

df = df.replace({np.nan: None})

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [ ]:
df = df.drop(columns=["shape"], errors="ignore")

In [ ]:
def fix_text(text):
    try:
        return text.encode('latin1').decode('utf-8')
    except:
        return text

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].apply(fix_text).str.strip().str.upper()

AttributeError: Can only use .str accessor with string values!

In [ ]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).apply(fix_text).str.strip().str.upper()

In [ ]:
print(df["tipo"].value_counts())
print(df["recorrido"].value_counts())
print(df["empresa"].value_counts().head())

tipo
DIRECTA CENTRO       155
INTEGRADA             55
DIRECTA NO CENTRO     20
CIRCULAR              19
Name: count, dtype: int64
recorrido
ORIGEN DESTINO_DESTINO ORIGEN    249
Name: count, dtype: int64
empresa
TRANSPORTE MEDELLÍN CASTILLA    34
PALENQUE ROBLEDAL               22
RÁPIDO SAN CRISTÓBAL            19
COONATRA                        17
CONDUCCIONES AMÉRICA            16
Name: count, dtype: int64

In [ ]:
df["recorrido"] = df["recorrido"].replace({
    "ORIGEN_DESTINO_DESTINO_ORIGEN": "ORIGEN_DESTINO"
})

In [ ]:
df["recorrido"].value_counts()

recorrido
ORIGEN DESTINO_DESTINO ORIGEN    249
Name: count, dtype: int64

In [ ]:
df["recorrido"] = df["recorrido"].replace({
    "ORIGEN DESTINO_DESTINO ORIGEN": "ORIGEN_DESTINO"
})

In [ ]:
df["recorrido"].value_counts()

recorrido
ORIGEN_DESTINO    249
Name: count, dtype: int64

In [ ]:
import pandas as pd

df = pd.read_csv(
    "velocidad_e_intensidad_vehicular_en_medellin.csv",
    encoding="latin-1",
    sep=";",
    engine="python",
    on_bad_lines="skip"
)

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431490 entries, 0 to 431489
Data columns (total 1 columns):
 #   Column                                                                                                                                                                                                                                                Non-Null Count   Dtype
---  ------                                                                                                                                                                                                                                                --------------   -----
 0   carril,fecha_trafico,fecha,hora,dia,dia_num,mes_num,mes,ano,velocidad_km_h,corredor,sentido,operacion,intensidad,categoria_1,categoria_2,categoria_3,ocupacion,tipo_subsistema,longitud,latitud,identificador_f_v,comuna,codigo_comuna,nombre_comuna  431490 non-null  object
dtypes: object(1)
memory usage: 3.3+ MB

  carril,fecha_trafico,fecha,hora,dia,dia_num,mes_num,mes,ano,velocidad_km_h,corredor,sentido,operacion,intensidad,categoria_1,categoria_2,categoria_3,ocupacion,tipo_subsistema,longitud,latitud,identificador_f_v,comuna,codigo_comuna,nombre_comuna
0  XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 0:00,1/07/20...
1  XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 1:00,1/07/20...
2  XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 2:00,1/07/20...
3  XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 3:00,1/07/20...
4  XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 4:00,1/07/20...

In [ ]:
df = pd.read_csv(
    "velocidad_e_intensidad_vehicular_en_medellin.csv",
    encoding="latin-1",
    sep=",",
    engine="python",
    on_bad_lines="skip"
)

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431490 entries, 0 to 431489
Data columns (total 25 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   carril             431490 non-null  object
 1   fecha_trafico      431490 non-null  object
 2   fecha              431490 non-null  object
 3   hora               431490 non-null  int64
 4   dia                431490 non-null  object
 5   dia_num            431490 non-null  int64
 6   mes_num            431490 non-null  int64
 7   mes                431490 non-null  object
 8   ano                431490 non-null  int64
 9   velocidad_km_h     431490 non-null  int64
 10  corredor           431490 non-null  object
 11  sentido            431490 non-null  object
 12  operacion          393940 non-null  object
 13  intensidad         431490 non-null  int64
 14  categoria_1        431490 non-null  int64
 15  categoria_2        431490 non-null  int64
 16  categoria_3        431490 non-null  int64
 17  ocupacion          431490 non-null  int64
 18  tipo_subsistema    431490 non-null  object
 19  longitud           431490 non-null  object
 20  latitud            431490 non-null  object
 21  identificador_f_v  431490 non-null  object
 22  comuna             405253 non-null  object
 23  codigo_comuna      431490 non-null  int64
 24  nombre_comuna      405253 non-null  object
dtypes: int64(11), object(14)
memory usage: 82.3+ MB

,carril,fecha_trafico,fecha,hora,dia,dia_num,mes_num,mes,ano,velocidad_km_h,...,categoria_2,categoria_3,ocupacion,tipo_subsistema,longitud,latitud,identificador_f_v,comuna,codigo_comuna,nombre_comuna
0,XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 0:00,1/07/2020,0,Miercoles,3,7,Julio,2020,27,...,9,3,15,ARS,"833291,8125","1182614,75",V,11 - Laureles Estadio,11,Laureles Estadio
1,XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 1:00,1/07/2020,1,Miercoles,3,7,Julio,2020,24,...,2,0,3,ARS,"833291,8125","1182614,75",V,11 - Laureles Estadio,11,Laureles Estadio
2,XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 2:00,1/07/2020,2,Miercoles,3,7,Julio,2020,21,...,1,1,4,ARS,"833291,8125","1182614,75",V,11 - Laureles Estadio,11,Laureles Estadio
3,XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 3:00,1/07/2020,3,Miercoles,3,7,Julio,2020,18,...,5,1,11,ARS,"833291,8125","1182614,75",V,11 - Laureles Estadio,11,Laureles Estadio
4,XC-1-BOL-65-ENT:ORI-OCC,1/07/2020 4:00,1/07/2020,4,Miercoles,3,7,Julio,2020,18,...,4,3,16,ARS,"833291,8125","1182614,75",V,11 - Laureles Estadio,11,Laureles Estadio

In [ ]:
import numpy as np

df = df.replace({np.nan: None})

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [ ]:
def fix_text(text):
    try:
        return text.encode('latin1').decode('utf-8')
    except:
        return text

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).apply(fix_text).str.strip().str.upper()

In [ ]:
def fix_text(text):
    try:
        return text.encode('latin1').decode('utf-8')
    except:
        return text

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).apply(fix_text).str.strip().str.upper()

In [ ]:
print(df.columns)

Index(['carril', 'fecha_trafico', 'fecha', 'hora', 'dia', 'dia_num', 'mes_num',
       'mes', 'ano', 'velocidad_km_h', 'corredor', 'sentido', 'operacion',
       'intensidad', 'categoria_1', 'categoria_2', 'categoria_3', 'ocupacion',
       'tipo_subsistema', 'longitud', 'latitud', 'identificador_f_v', 'comuna',
       'codigo_comuna', 'nombre_comuna'],
      dtype='object')

In [ ]:
print(df.columns)

Index(['carril', 'fecha_trafico', 'fecha', 'hora', 'dia', 'dia_num', 'mes_num',
       'mes', 'ano', 'velocidad_km_h', 'corredor', 'sentido', 'operacion',
       'intensidad', 'categoria_1', 'categoria_2', 'categoria_3', 'ocupacion',
       'tipo_subsistema', 'longitud', 'latitud', 'identificador_f_v', 'comuna',
       'codigo_comuna', 'nombre_comuna'],
      dtype='object')

In [ ]:
df["operacion"].value_counts()

operacion
INTERRUMPIDO       274876
CONTINUO            85425
NONE                37550
SEMINTERRUMPIDO     33639
Name: count, dtype: int64

In [ ]:
print(df["operacion"].value_counts())
print(df["sentido"].value_counts())
print(df["dia"].value_counts())

operacion
INTERRUMPIDO       274876
CONTINUO            85425
NONE                37550
SEMINTERRUMPIDO     33639
Name: count, dtype: int64
sentido
SN       149580
NS       119184
WE        68415
EW        67962
0         23416
WE-EW      2192
NS-SN       741
Name: count, dtype: int64
dia
JUEVES       67923
MIERCOLES    67772
VIERNES      66989
DOMINGO      57772
LUNES        57633
SABADO       57421
MARTES       55980
Name: count, dtype: int64

In [ ]:
df["operacion"] = df["operacion"].replace("NONE", None)

In [ ]:
df["sentido"] = df["sentido"].replace({
    "0": None,
    "WE-EW": "WE",
    "NS-SN": "NS"
})

In [ ]:
print(df["operacion"].value_counts(dropna=False))
print(df["sentido"].value_counts(dropna=False))

operacion
INTERRUMPIDO       274876
CONTINUO            85425
None                37550
SEMINTERRUMPIDO     33639
Name: count, dtype: int64
sentido
SN      149580
NS      119925
WE       70607
EW       67962
None     23416
Name: count, dtype: int64

In [ ]:
df["operacion"] = df["operacion"].replace("None", None)
df["sentido"] = df["sentido"].replace("None", None)

In [ ]:
(df["operacion"] == "None").sum()
(df["sentido"] == "None").sum()

np.int64(0)

In [ ]:
(df["operacion"] == "None").sum()
(df["sentido"] == "None").sum()

np.int64(0)

In [ ]:
df["operacion"].isnull().sum()
df["sentido"].isnull().sum()

np.int64(23416)

In [ ]:
(df["operacion"] == "None").sum()
(df["sentido"] == "None").sum()

np.int64(0)

In [ ]:
df.to_csv("/content/drive/MyDrive/RetoEafit/limpios/intensidad_limpia_final.csv", index=False)

In [ ]:
import pandas as pd

df = pd.read_csv(
    "incidentes_viales.csv",
    encoding="latin-1",
    sep=";",
    engine="python",
    on_bad_lines="skip"
)

df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270765 entries, 0 to 270764
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   AÑO                    270765 non-null  int64
 1   CBML                   252609 non-null  object
 2   CLASE_ACCIDENTE        270759 non-null  object
 3   DIRECCION              270765 non-null  object
 4   DIRECCION ENCASILLADA  270374 non-null  object
 5   DISEÃO                269617 non-null  object
 6   EXPEDIENTE             270655 non-null  object
 7   FECHA_ACCIDENTE        270765 non-null  object
 8   FECHA_ACCIDENTES       270765 non-null  object
 9   GRAVEDAD_ACCIDENTE     270765 non-null  object
 10  MES                    270765 non-null  int64
 11  NRO_RADICADO           270760 non-null  object
 12  NUMCOMUNA              270765 non-null  object
 13  BARRIO                 251759 non-null  object
 14  COMUNA                 257967 non-null  object
 15  LOCATION               270765 non-null  object
 16  X                      270765 non-null  object
 17  Y                      270765 non-null  object
dtypes: int64(2), object(16)
memory usage: 37.2+ MB

,AÑO,CBML,CLASE_ACCIDENTE,DIRECCION,DIRECCION ENCASILLADA,DISEÃO,EXPEDIENTE,FECHA_ACCIDENTE,FECHA_ACCIDENTES,GRAVEDAD_ACCIDENTE,MES,NRO_RADICADO,NUMCOMUNA,BARRIO,COMUNA,LOCATION,X,Y
0,2015,1013,Caida Ocupante,CR 46 CL 43,CR 046 043 000 00000,Tramo de via,A000259731,21/10/2015 5:58,2015-10-21T10:58:00.000Z,Con heridos,10,1508668,10,Barrio ColÃ³n,La Candelaria,"[-75.5688011014, 6.24312304123]",834949.69,1182357.34
1,2015,1020,Choque,CR 43 A CL 29,CR 043 A 029 000 00000,Tramo de via,A000261725,5/11/2015 3:00,2015-11-05T08:00:00.000Z,Solo daños,11,1510621,10,San Diego,La Candelaria,"[-75.5693883283, 6.22870030622]",834880.17,1180762.02
2,2015,205,Otro,CR 46 CL 37,CR 046 037 000 00000,Tramo de via,A000259739,21/10/2015 7:40,2015-10-21T12:40:00.000Z,Con heridos,10,1508691,2,La Francia,Santa Cruz,"[-75.5503911403, 6.29869502502]",837004.94,1188499.17
3,2015,101,Atropello,CR 34 CL 112,CR 034 112 000 00000,Tramo de via,A000259752,21/10/2015 12:00,2015-10-21T17:00:00.000Z,Con heridos,10,1508694,1,Santo Domingo Savio No. 1,Popular,"[-75.5442195069, 6.30019383306]",837688.53,1188663.05
4,2015,1504,Choque,CR 50 CL 14,CR 050 014 000 00000,Tramo de via,A000259949,3/11/2015 6:16,2015-11-03T11:16:00.000Z,Solo daños,11,1510634,15,Santa FÃ©,Guayabal,"[-75.578180998, 6.21699243701]",833903.11,1179469.6

In [ ]:
import numpy as np

df = df.replace({np.nan: None})

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [ ]:
def fix_text(text):
    try:
        return text.encode('latin1').decode('utf-8')
    except:
        return text

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).apply(fix_text).str.strip().str.upper()

In [ ]:
df.head()

,año,cbml,clase_accidente,direccion,direccion_encasillada,diseão,expediente,fecha_accidente,fecha_accidentes,gravedad_accidente,mes,nro_radicado,numcomuna,barrio,comuna,location,x,y
0,2015,1013,CAIDA OCUPANTE,CR 46 CL 43,CR 046 043 000 00000,TRAMO DE VIA,A000259731,21/10/2015 5:58,2015-10-21T10:58:00.000Z,CON HERIDOS,10,1508668,10,BARRIO COLÓN,LA CANDELARIA,"[-75.5688011014, 6.24312304123]",834949.69,1182357.34
1,2015,1020,CHOQUE,CR 43 A CL 29,CR 043 A 029 000 00000,TRAMO DE VIA,A000261725,5/11/2015 3:00,2015-11-05T08:00:00.000Z,SOLO DAÑOS,11,1510621,10,SAN DIEGO,LA CANDELARIA,"[-75.5693883283, 6.22870030622]",834880.17,1180762.02
2,2015,205,OTRO,CR 46 CL 37,CR 046 037 000 00000,TRAMO DE VIA,A000259739,21/10/2015 7:40,2015-10-21T12:40:00.000Z,CON HERIDOS,10,1508691,2,LA FRANCIA,SANTA CRUZ,"[-75.5503911403, 6.29869502502]",837004.94,1188499.17
3,2015,101,ATROPELLO,CR 34 CL 112,CR 034 112 000 00000,TRAMO DE VIA,A000259752,21/10/2015 12:00,2015-10-21T17:00:00.000Z,CON HERIDOS,10,1508694,1,SANTO DOMINGO SAVIO NO. 1,POPULAR,"[-75.5442195069, 6.30019383306]",837688.53,1188663.05
4,2015,1504,CHOQUE,CR 50 CL 14,CR 050 014 000 00000,TRAMO DE VIA,A000259949,3/11/2015 6:16,2015-11-03T11:16:00.000Z,SOLO DAÑOS,11,1510634,15,SANTA FÉ,GUAYABAL,"[-75.578180998, 6.21699243701]",833903.11,1179469.6

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270765 entries, 0 to 270764
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   año                    270765 non-null  int64
 1   cbml                   270765 non-null  object
 2   clase_accidente        270765 non-null  object
 3   direccion              270765 non-null  object
 4   direccion_encasillada  270765 non-null  object
 5   diseão                270765 non-null  object
 6   expediente             270765 non-null  object
 7   fecha_accidente        270765 non-null  object
 8   fecha_accidentes       270765 non-null  object
 9   gravedad_accidente     270765 non-null  object
 10  mes                    270765 non-null  int64
 11  nro_radicado           270765 non-null  object
 12  numcomuna              270765 non-null  object
 13  barrio                 270765 non-null  object
 14  comuna                 270765 non-null  object
 15  location               270765 non-null  object
 16  x                      270765 non-null  object
 17  y                      270765 non-null  object
dtypes: int64(2), object(16)
memory usage: 37.2+ MB

In [ ]:
df = df.rename(columns={
    "diseão": "diseno",
    "aÃ±o": "ano"  # por si también aparece
})

In [ ]:
print(df.columns)

Index(['año', 'cbml', 'clase_accidente', 'direccion', 'direccion_encasillada',
       'diseno', 'expediente', 'fecha_accidente', 'fecha_accidentes',
       'gravedad_accidente', 'mes', 'nro_radicado', 'numcomuna', 'barrio',
       'comuna', 'location', 'x', 'y'],
      dtype='object')

In [ ]:
df.to_csv("/content/drive/MyDrive/RetoEafit/limpios/incidentes_limpia_final.csv", index=False)

In [ ]:
!pip install supabase --quiet

from supabase import create_client

SUPABASE_URL = "https://dutltpmxhiqltrfidvkq.supabase.co"
SUPABASE_KEY = "sb_publishable_Y6kPw651Ue-oktcUPyhTMA_Th-RTWvW"

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

print("Conectado a Supabase ✅")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 3.7 MB/s eta 0:00:00
Conectado a Supabase ✅

In [ ]:
subir_tabla(
    "/content/drive/MyDrive/RetoEafit/limpios/camaras_limpia_final.csv",
    "Camaras"
)

APIError: {'message': "Could not find the 'direccion' column of 'Camaras' in the schema cache", 'code': 'PGRST204', 'hint': None, 'details': None}